---

- name: zip logs
  archive:
    path: ./webapps/{{ item }}/storage/logs
    dest: ./webapps/{{ item }}/{{ item }}.tar.gz
    format: gz
  with_items: "{{ webapps }}"

- name: download backup zip
  fetch:
    src: ./webapps/{{ item }}/{{ item }}.tar.gz
    dest: /home/hugo/backups/logs/{{ ansible_date_time.date }}/
    flat: yes
  with_items: "{{ webapps }}"

- name: clear logs
  shell: /bin/rm ./webapps/{{ item }}/storage/logs/*
  with_items: "{{ webapps }}"

- name: clear logs backup
  file: path=./webapps/{{ item }}/{{ item }}.tar.gz state=absent
  with_items: "{{ webapps }}"