---

- name: download files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - url: "https://mms.alliedmods.net/mmsdrop/1.11/mmsource-1.11.0-git1131-linux.tar.gz"
      dest: /tmp/mm.tar.gz
    - url: "https://sm.alliedmods.net/smdrop/1.10/sourcemod-1.10.0-git6490-linux.tar.gz"
      dest: /tmp/sm.tar.gz


- name: ensure extraction directories exists
  file:
    path: /tmp/{{ item }}
    state: directory
  with_items:
    - mm
    - sm


- name: unzip
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  loop:
    - src: /tmp/mm.tar.gz
      dest: /tmp/mm/
    - src: /tmp/sm.tar.gz
      dest: /tmp/sm/


- name: copy metamod
  synchronize:
    src: /tmp/mm/
    dest: /tmp/merged
  delegate_to: "{{ inventory_hostname }}"


- name: copy sourcemod
  synchronize:
    src: /tmp/sm/
    dest: /tmp/merged
  delegate_to: "{{ inventory_hostname }}"


- stat:
    path: /tmp/merged/addons/metamod/sourcemod.vdf
  register: missing

- debug: var=missing