---

- name: configure sourcemod core
  template:
    src: core.cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/core.cfg.ansible"

- name: configure sourcemod admin overrides
  template:
    src: sm-cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/admin_overrides.cfg.ansible"
  vars:
    data:
      Overrides: "{{ sm_overrides | default({}) }}"

- name: configure sourcemod admin simple
  template:
    src: admins-simple.ini.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/admins_simple.ini"
  vars:
    admins: "{{ sm_admins_simple | default({}) }}"

- name: configure sourcemod databases
  template:
    src: sm-cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/databases.cfg"
  vars:
    data:
      Databases: "{{ sm_databases | default({}) }}"

- name: configure basevotes plugin
  template:
    src: basevotes.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/basevotes.cfg"

- name: configure fun commands plugin
  template:
    src: funcommands.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/funcommands.cfg"

- name: configure fun votes plugin
  template:
    src: funvotes.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/funvotes.cfg"

- name: generate /cfg configs
  template:
    src: cvar-cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/{{ item.key }}"
  vars:
    data: "{{ item.value }}"
  loop: "{{ sm_cvars | default({}) | dict2items }}"
