---

- name: Configure SourceMod core
  template:
    src: core.cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/core.cfg"

- name: Configure SourceMod admin overrides
  template:
    src: sm-cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/admin_overrides.cfg"
  vars:
    data:
      Overrides: "{{ sm_overrides | default({}) }}"

- name: Configure SourceMod admin simple
  template:
    src: admins-simple.ini.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/admins_simple.ini"
  vars:
    admins: "{{ sm_admins_simple | default({}) }}"

- name: Configure SourceMod databases
  template:
    src: sm-cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/databases.cfg"
  vars:
    data:
      Databases: "{{ sm_databases | default({}) }}"

- name: Configure basevotes.smx
  template:
    src: basevotes.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/basevotes.cfg"

- name: Configure funcommands.smx
  template:
    src: funcommands.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/funcommands.cfg"

- name: Configure funvotes.smx
  template:
    src: funvotes.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/funvotes.cfg"

- name: Configure Sourcemod
  template:
    src: sourcemod.cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/sourcemod.cfg"

- name: Generate /csgo/cfg files
  template:
    src: cvar-cfg.j2
    dest: "{{ csgo_root }}/csgo/cfg/{{ item.key }}"
  vars:
    data: "{{ item.value }}"
  loop: "{{ sm_cvars | default({}) | dict2items }}"

- name: Generate maplist.txt
  template:
    src: map-cfg.j2
    dest: "{{ csgo_root }}/csgo/maplist.txt"
  vars:
    data: "{{ maplist }}"

- name: Generate mapcycle.txt
  template:
    src: map-cfg.j2
    dest: "{{ csgo_root }}/csgo/mapcycle.txt"
  vars:
    data: "{{ mapcycle }}"