---

- name: install deathmatch loader
  include_tasks: install-deathmatch-loader.yml
  vars:
    plugin_id: dml
    plugin_url: "{{ dml_download_url }}"
    skip_basepath: yes
    addons_diretories:
      - plugins
      - scripting