---

- name: download files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
    force: yes
  loop:
    - url: "{{ mm_download_url }}"
      dest: /tmp/mm.tar.gz
    - url: "{{ sm_download_url }}"
      dest: /tmp/sm.tar.gz


- name: ensure extraction directories exists
  file:
    path: "/tmp/{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - mm
    - sm


- name: unzip
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  loop:
    - src: /tmp/mm.tar.gz
      dest: /tmp/mm/
    - src: /tmp/sm.tar.gz
      dest: /tmp/sm/


- name: install metamod
  synchronize:
    src: /tmp/mm/
    dest: "{{ csgo_root }}/csgo/"
  delegate_to: "{{ inventory_hostname }}"


- name: install sourcemod
  synchronize:
    src: /tmp/sm/
    dest: "{{ csgo_root }}/csgo/"
  delegate_to: "{{ inventory_hostname }}"