---

- name: Install multi1v1
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: arena
    plugin_url: "{{ arena_download_url }}"
    addons_basepath: addons/sourcemod/
    cfg_basepath: cfg/sourcemod/
    addons_diretories:
      - configs
      - plugins
      - scripting
      - translations
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/multi1v1_customrounds.cfg
        data:
          CustomRoundTypes: "{{ arena_custom_rounds | default({}) }}"
      - src: sm-cfg.j2
        dest: configs/multi1v1_weapons.cfg
        data:
          Weapons: "{{ arena_weapons | default({}) }}"
    cfg_directories:
      - multi1v1
    cfg_templates:
      - src: cvar-cfg.j2
        dest: multi1v1/game_cvars.cfg
        data: "{{ arena_cvars | default([]) }}"
      - src: multi1v1.cfg.j2
        dest: multi1v1/multi1v1.cfg