---

- name: Download files
  get_url:
    url: "{{ plugin_url }}"
    dest: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}.zip"
    force: yes

- name: Ensure extraction directory is clean
  file:
    path: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/"
    state: absent

- name: Create extraction directory
  file:
    path: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/"
    state: directory
    mode: "{{ default_mode | default('0755') }}"

- name: Unzip
  unarchive:
    src: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}.zip"
    dest: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/"
    remote_src: yes

- name: Find root directory path that was created unzipping the plugin
  find:
    paths: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/"
    file_type: directory
  register: basefiles
  when: ignore_first_directory|default(false)|bool

- name: Extract directory path
  set_fact:
    weird_github_dir: "{{ basefiles.files[0].path }}/"
  when: ignore_first_directory|default(false)|bool

- name: Set basepath to plugins
  set_fact:
    base: "{{ weird_github_dir }}"
    addons_base: "{{ weird_github_dir }}{{ addons_basepath | default('') }}"
    cfg_base: "{{ weird_github_dir }}{{ cfg_basepath | default('') }}"
  when: ignore_first_directory|default(false)|bool

- name: Set basepath to plugins
  set_fact:
    base: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/"
    addons_base: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/{{ addons_basepath | default('') }}"
    cfg_base: "/tmp/{{ inventory_hostname }}/{{ plugin_id }}/{{ cfg_basepath | default('') }}"
  when: not (ignore_first_directory|default(false)|bool)


- name: Copy /csgo/addons/ directories
  copy:
    src: "{{ addons_base }}{{ item }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/"
    remote_src: yes
    mode: "{{ default_mode | default('0755') }}"
    directory_mode: "{{ default_directory_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  when: "'when' not in item or item.when"
  with_items: "{{ addons_diretories | default([]) }}"

- name: Copy /csgo/addons/ files
  copy:
    src: "{{ addons_base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/{{ item.dest }}"
    remote_src: yes
    mode: "{{ default_mode | default('0755') }}"
    directory_mode: "{{ default_directory_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  when: "'when' not in item or item.when"
  with_items: "{{ addons_files | default({}) }}"

- name: Copy /csgo/addons/ templates
  template:
    src: "{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/{{ item.dest }}"
    mode: "{{ default_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  vars:
    data: "{{ item.data | default({}) }}"
  when: "'when' not in item or item.when"
  with_items: "{{ addons_templates | default({}) }}"

- name: Create /csgo/cfg/ directories
  file:
    path: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item }}"
    state: directory
    mode: "{{ default_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  with_items: "{{ cfg_directories | default([]) }}"

- name: Copy /csgo/cfg/ templates
  template:
    src: "{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item.dest }}"
    mode: "{{ default_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  when: "'when' not in item or item.when"
  with_items: "{{ cfg_templates | default({}) }}"

- name: Copy /csgo/cfg/ files
  copy:
    src: "{{ cfg_base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item.dest }}"
    remote_src: yes
    mode: "{{ default_mode | default('0755') }}"
    directory_mode: "{{ default_directory_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  when: "'when' not in item or item.when"
  with_items: "{{ cfg_files | default({}) }}"

- name: Create /csgo/ directories
  file:
    path: "{{ csgo_root }}/csgo/{{ item }}"
    state: directory
    mode: "{{ default_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  with_items: "{{ other_directories | default([]) }}"

- name: Copy other files
  copy:
    src: "{{ base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/{{ item.dest }}"
    remote_src: yes
    mode: "{{ default_mode | default('0755') }}"
    directory_mode: "{{ default_directory_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  when: "'when' not in item or item.when"
  with_items: "{{ other_files | default({}) }}"
