---

- name: Install Server Redirect
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: sr
    plugin_url: "{{ sr_download_url }}"
    addons_basepath: addons/sourcemod/
    addons_diretories:
      - gamedata
      - scripting
      - plugins
      - translations
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/server_redirect.cfg
        data:
          Servers: "{{ sr_config }}"