---

- name: Install KZTimer
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: kz
    plugin_url: "{{ kz_download_url }}"
    addons_basepath: addons/sourcemod/
    cfg_basepath: cfg/sourcemod
    addons_diretories:
      - configs
      - plugins
      - gamedata
      - scripting
      - translations
    other_directories:
      - sound
    other_files:
      - src: cfg/
        dest: cfg/
      - src: maps/
        dest: maps/
      - src: materials/
        dest: materials/
      - src: models/
        dest: models/
      - src: sound/
        dest: sound/