---

- name: download files
  get_url:
    url: "{{ plugin_url }}"
    dest: "/tmp/{{ plugin_id }}.zip"
    force: yes

- name: ensure extraction directories exists
  file:
    path: "/tmp/{{ plugin_id }}/"
    state: directory
    mode: 0755

- name: unzip
  unarchive:
    src: "/tmp/{{ plugin_id }}.zip"
    dest: "/tmp/{{ plugin_id }}/"
    remote_src: yes

- name: find root directory path that was created unzipping the plugin
  find:
    paths: "/tmp/{{ plugin_id }}/"
    file_type: directory
  register: basefiles
  when: ignore_first_directory|default(false)|bool

- name: extract directory path
  set_fact:
    weird_github_dir: "{{ basefiles.files[0].path }}/"
  when: ignore_first_directory|default(false)|bool

- name: set basepath to plugins
  set_fact:
    base: "{{ weird_github_dir }}"
    addons_base: "{{ weird_github_dir }}{{ addons_basepath | default('') }}"
    cfg_base: "{{ weird_github_dir }}{{ cfg_basepath | default('') }}"
  when: ignore_first_directory|default(false)|bool

- name: set basepath to plugins
  set_fact:
    base: "/tmp/{{ plugin_id }}/"
    addons_base: "/tmp/{{ plugin_id }}/{{ addons_basepath | default('') }}"
    cfg_base: "/tmp/{{ plugin_id }}/{{ cfg_basepath | default('') }}"
  when: not (ignore_first_directory|default(false)|bool)


- name: copy addons/ directories
  copy:
    src: "{{ addons_base }}{{ item }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl
  with_items: "{{ addons_diretories | default([]) }}"

- name: copy addons/ files
  copy:
    src: "{{ addons_base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/{{ item.dest }}"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl
  with_items: "{{ addons_files | default({}) }}"

- name: copy addons/ templates
  template:
    src: "{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/{{ item.dest }}"
  vars:
    data: "{{ item.data | default({}) }}"
  with_items: "{{ addons_templates | default({}) }}"

- name: create cfg/ directories
  file:
    path: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item }}"
    state: directory
  with_items: "{{ cfg_directories | default([]) }}"

- name: copy cfg/ templates
  template:
    src: "{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item.dest }}"
  with_items: "{{ cfg_templates | default({}) }}"

- name: copy cfg/ files
  copy:
    src: "{{ cfg_base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item.dest }}"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl
  with_items: "{{ cfg_files | default({}) }}"

- name: copy other files
  copy:
    src: "{{ base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/{{ item.dest }}"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl
  with_items: "{{ other_files | default({}) }}"