---

- name: install abner killfeed filter
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: akf
    plugin_url: "{{ akf_download_url }}"
    ignore_first_directory: yes
    addons_diretories:
      - plugins
      - scripting
    cfg_templates:
      - src: abner_killfeed_filter.cfg.j2
        dest: abner_killfeed_filter.cfg