---


- name: install kento rankme
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: srm
    plugin_url: "{{ srm_download_url }}"
    addons_diretories:
      - plugins
      - scripting