---

- name: install deathmatch loader
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: dml
    plugin_url: "{{ dml_download_url }}"
    addons_diretories:
      - plugins
      - scripting