---

- name: Install ServerAdvertisements3
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: sa3
    plugin_url: "{{ sa3_download_url }}"
    addons_diretories:
      - plugins
      - scripting
      - configs
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/ServerAdvertisements3.cfg
        data:
          ServerAdvertisements3: "{{ sa3_config }}"
    cfg_templates:
      - src: ServerAdvertisements3.cfg.j2
        dest: ServerAdvertisements3.cfg