---

- name: Install GeoIP City
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: gipc
    plugin_url: "{{ gipc_download_url }}"
    addons_diretories:
      - extensions
      - scripting

- name: Download GeoIPCity.zip
  get_url:
    url: https://share.snksrv.com/f/ypA7GK.zip
    dest: "/tmp/{{ inventory_hostname }}/geoipcity.zip"

- name: Ensure extraction directory exists
  file:
    path: "/tmp/{{ inventory_hostname }}/geoipcity/"
    state: directory
    mode: "{{ default_mode | default('0755') }}"

- name: Unzip GeoIPCity
  unarchive:
    src: "/tmp/{{ inventory_hostname }}/geoipcity.zip"
    dest: "/tmp/{{ inventory_hostname }}/geoipcity/"
    remote_src: yes

- name: Copy GeoIPCity.dat
  copy:
    src: "/tmp/{{ inventory_hostname }}/geoipcity/GeoIPCity.dat"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/geoip/"
    remote_src: yes
    mode: "{{ default_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"