---

- name: Install HexTags
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: hex
    plugin_url: "{{ hex_download_url }}"
    addons_basepath: addons/sourcemod/
    addons_diretories:
      - plugins
      - scripting
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/hextags.cfg
        data:
          HexTags: "{{ hex_config | default({}) }}"
    cfg_templates:
      - src: plugin.hextags.cfg.j2
        dest: plugin.hextags.cfg