---

- name: Download files
  get_url:
    url: "{{ surf_download_url }}"
    dest: "/tmp/surf.zip"
    force: yes

- name: Ensure extraction directory is clean
  file:
    path: "/tmp/surf/"
    state: absent

- name: Create extraction directory
  file:
    path: "/tmp/surf/"
    state: directory
    mode: 0755

- name: Unzip
  unarchive:
    src: "/tmp/surf.zip"
    dest: "/tmp/surf/"
    remote_src: yes

- name: Find root directory path that was created unzipping the plugin
  find:
    paths: "/tmp/surf/"
    file_type: directory
  register: basefiles

- name: Extract directory path
  set_fact:
    weird_github_dir: "{{ basefiles.files[0].path }}/"

- name: Set basepath to plugins
  set_fact:
    base: "{{ weird_github_dir }}"
    addons_base: "{{ weird_github_dir }}addons/sourcemod/"
    cfg_base: "{{ weird_github_dir }}{{ cfg_basepath | default('') }}"

- name: Copy /csgo/addons/ directories
  copy:
    src: "{{ addons_base }}{{ item }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl
  with_items:
    - configs
    - scripting
    - translations

- name: Download plugin
  get_url:
    url: "{{ surf_smx_download_url }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/SurfTimer.smx"
    force: yes

- name: Download plugin
  get_url:
    url: "{{ surf_discord_download_url }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/discord_api.smx"
    force: yes

- name: Copy replay_bot.nav
  copy:
    src: "{{ base }}/maps/replay_bot.nav"
    dest: "{{ csgo_root }}/csgo/maps/"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl

- name: Copy sounds
  copy:
    src: "{{ base }}/sound/"
    dest: "{{ csgo_root }}/csgo"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl

- name: Copy static configs
  copy:
    src: "{{ base }}/cfg/"
    dest: "{{ csgo_root }}/csgo/cfg/"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl