---

- name: install togs clantags
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: tct
    plugin_url: "{{ tct_download_url }}"
    ignore_first_directory: yes
    addons_diretories:
      - plugins
      - scripting
      - configs
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/togsclantags.cfg
        data:
          Setups: "{{ tct_config | default({}) }}"
    cfg_templates:
      - src: togsclantags.cfg.j2
        dest: togsclantags.cfg