---

- name: Install Deathmatch Loader
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: dml
    plugin_url: "{{ dml_download_url }}"
    addons_diretories:
      - plugins
      - scripting
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/deathmatch/config_loader.ini
        data:
          Config: "{{ dm_loader_config | default({}) }}"
      - src: sm-cfg.j2
        dest: configs/multi1v1_weapons.cfg
        data:
          Weapons: "{{ arena_weapons | default({}) }}"

- name: generate deathmatch configs
  template:
    src: sm-cfg.j2
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/configs/deathmatch/{{ item.key }}"
    mode: "{{ default_mode | default('0755') }}"
    owner: "{{ default_owner | default('pterodactyl') }}"
    group: "{{ default_group | default('pterodactyl') }}"
  vars:
    data:
      Deathmatch Config: "{{ item.value | default({}) }}"
  with_items: "{{ dm_config | default({}) | dict2items }}"