---

- name: Install AFK Manager
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: afkm
    plugin_url: "{{ afkm_download_url }}"
    addons_diretories:
      - plugins
      - scripting
      - translations
    cfg_templates:
      - src: afk_manager.cfg.j2
        dest: afk_manager.cfg