---

- name: Make sure extraction diretories exist
  file:
    path: "/tmp/{{ inventory_hostname }}/"
    state: directory
    mode: "{{ default_mode | default('0755') }}"

- name: Download files
  get_url:
    url: "{{ item.url }}"
    dest: "{{ item.dest }}"
  loop:
    - url: "{{ mm_download_url }}"
      dest: "/tmp/{{ inventory_hostname }}/mm.tar.gz"
    - url: "{{ sm_download_url }}"
      dest: "/tmp/{{ inventory_hostname }}/sm.tar.gz"

- name: Cleanup extraction directories
  file:
    path: "/tmp/{{ inventory_hostname }}/{{ item }}"
    state: absent
  with_items:
    - mm
    - sm

- name: Create extraction directories
  file:
    path: "/tmp/{{ inventory_hostname }}/{{ item }}"
    state: directory
    mode: "{{ default_mode | default('0755') }}"
  with_items:
    - mm
    - sm

- name: Unzip
  unarchive:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    remote_src: yes
  loop:
    - src: "/tmp/{{ inventory_hostname }}/mm.tar.gz"
      dest: "/tmp/{{ inventory_hostname }}/mm/"
    - src: "/tmp/{{ inventory_hostname }}/sm.tar.gz"
      dest: "/tmp/{{ inventory_hostname }}/sm/"

- name: Install metamod
  synchronize:
    src: "/tmp/{{ inventory_hostname }}/mm/"
    dest: "{{ csgo_root }}/csgo/"
  delegate_to: "{{ inventory_hostname }}"

- name: Install sourcemod
  synchronize:
    src: "/tmp/{{ inventory_hostname }}/sm/"
    dest: "{{ csgo_root }}/csgo/"
  delegate_to: "{{ inventory_hostname }}"

- name: Rnable disabled plugins
  copy:
    src: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/disabled/{{ item }}.smx"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/{{ item }}.smx"
    remote_src: yes
  with_items: "{{ sm_enable_plugins | default([]) }}"

- name: Copy default plugins to disabled directory
  copy:
    src: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/{{ item }}.smx"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/disabled/{{ item }}.smx"
    remote_src: yes
  with_items: "{{ sm_disable_plugins | default([]) }}"

- name: Delete disabled default plugins
  file:
    path: "{{ csgo_root }}/csgo/addons/sourcemod/plugins/{{ item }}.smx"
    state: absent
  with_items: "{{ sm_disable_plugins | default([]) }}"
