---

- name: install abner reset score
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: ars
    plugin_url: "{{ ars_download_url }}"
    addons_basepath: addons/sourcemod/
    addons_diretories:
      - plugins
      - scripting
      - translations
    cfg_templates:
      - src: plugin.abner_resetscore.cfg.j2
        dest: plugin.abner_resetscore.cfg