---

- name: Install Deathmatch v3
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: dm3
    plugin_url: "{{ dm3_download_url }}"
    addons_diretories:
      - plugins
      - scripting
      - configs
      - translations
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/deathmatch/deathmatch.ini
        data:
          Deathmatch Config: "{{ dm3_config | default({}) }}"