---

- name: include default vars
  include_vars: dm-defaults.yml

- name: install deathmatch
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: dm
    plugin_url: "{{ dm_download_url }}"
    addons_diretories:
      - plugins
      - scripting
      - configs
      - translations
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/deathmatch/deathmatch.ini
        data:
          Deathmatch Config: "{{ dm_config }}"