---

- name: install chat processor
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: cp
    plugin_url: "{{ cp_download_url }}"
    addons_diretories:
      - configs
      - plugins
      - scripting
    cfg_templates:
      - src: chat-processor.cfg.j2
        dest: chat-processor.cfg