---

- name: Install restart empty
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: re
    plugin_url: "{{ re_download_url }}"
    addons_diretories:
      - plugins
      - scripting
    cfg_templates:
      - src: sm_restart_empty.cfg.j2
        dest: sm_restart_empty.cfg