---

- name: install restart empty
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: re
    plugin_url: "{{ re_download_url }}"
    addons_diretories:
      - plugins
      - scripting