---

- name: Install arena crashifix
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: acf
    plugin_url: "{{ acf_download_url }}"
    ignore_first_directory: yes
    addons_files:
      - src: mapcrashfixer.smx
        dest: plugins/mapcrashfixer.smx

      - src: mapcrashfixer.sp
        dest: scripting/mapcrashfixer.sp