---

- name: Install Kento RankME
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: rankme
    plugin_url: "{{ sm_rankme_url }}"
    ignore_first_directory: yes
    addons_diretories:
      - plugins
      - scripting
      - translations
    cfg_templates:
      - src: kento.rankme.cfg.j2
        dest: kento.rankme.cfg