---

- debug: var=plugin_url

- name: download files
  get_url:
    url: "{{ plugin_url }}"
    dest: "/tmp/{{ plugin_id }}.zip"
    force: yes


- name: ensure extraction directories exists
  file:
    path: "/tmp/{{ plugin_id }}/"
    state: directory
    mode: 0755


- name: unzip
  unarchive:
    src: "/tmp/{{ plugin_id }}.zip"
    dest: "/tmp/{{ plugin_id }}/"
    remote_src: yes


- name: find root directory path that was created unzipping the plugin
  find:
    paths: "/tmp/{{ plugin_id }}/"
    file_type: directory
  register: basefiles
  when: not (skip_basepath|default(false)|bool)


- name: extract directory path
  set_fact:
    plugin_base: "{{ basefiles.files[0].path }}/"
  when: not (skip_basepath|default(false)|bool)


- name: set basepath to plugins
  set_fact:
    plugin_base: "/tmp/{{ plugin_id }}/{{ basepath | default('') }}"
    cfg_base: "/tmp/{{ plugin_id }}/{{ cfg_basepath | default('') }}"
  when: skip_basepath|default(false)|bool


- name: copy files to server
  copy:
    src: "{{ plugin_base }}{{ item }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/"
    remote_src: yes
    mode: 0755
    directory_mode: 0755
    owner: pterodactyl
    group: pterodactyl
  with_items: "{{ addons_diretories | default([]) }}"


- name: install addons/ templates
  template:
    src: "{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/{{ item.dest }}"
  vars:
    data: "{{ item.data | default({}) }}"
  with_items: "{{ addons_templates | default({}) }}"


- name: create cfg/ directories
  file:
    path: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item }}"
    state: directory
  with_items: "{{ cfg_directories | default([]) }}"


- name: install cfg/ templates
  template: 
    src: "{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item.dest }}"
  with_items: "{{ cfg_templates | default({}) }}"


- name: install cfg/ files
  copy:
    src: "{{ cfg_base }}{{ item.src }}"
    dest: "{{ csgo_root }}/csgo/cfg/sourcemod/{{ item.dest }}"
    remote_src: yes
  with_items: "{{ cfg_files | default({}) }}"