---

- name: install calladmin
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: ca
    plugin_url: "{{ ca_download_url }}"
    addons_diretories:
      - plugins
      - scripting
      - translations
    cfg_templates:
      - src: plugin.calladmin.cfg.j2
        dest: plugin.calladmin.cfg