---

- name: install kgns weapons
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: wep
    plugin_url: "{{ wep_download_url }}"
    skip_basepath: yes
    addons_basepath: addons/sourcemod/
    addons_diretories:
      - configs
      - plugins
      - scripting
      - translations
    cfg_templates:
      - src: weapons.cfg.j2
        dest: weapons.cfg