---

- name: Install Executes
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: exec
    plugin_url: "{{ exec_download_url }}"
    addons_basepath: addons/sourcemod/
    cfg_basepath: cfg/sourcemod/
    addons_diretories:
      - configs
      - plugins
      - scripting
      - translations
    cfg_directories:
      - executes
    cfg_files:
      - src: executes/executes_game.cfg
        dest: executes/executes_game.cfg
    cfg_templates:
      - src: executes.cfg.j2
        dest: executes/executes.cfg

- name: fix chinese translations
  get_url:
    url: https://raw.githubusercontent.com/HugoJF/csgo-executes/master/translations/chi/executes.phrases.txt
    dest: "{{ csgo_root }}/csgo/addons/sourcemod/translations/chi/executes.phrases.txt"
    force: yes
