---

- name: Install kgns gloves
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: glo
    plugin_url: "{{ glo_download_url }}"
    addons_diretories:
      - configs
      - plugins
      - scripting
      - translations
    cfg_templates:
      - src: gloves.cfg.j2
        dest: gloves.cfg