---

- name: Install Skybox
  include_tasks: install-plugin-github.yml
  vars:
    plugin_id: skybox
    plugin_url: "{{ skybox_download_url }}"
    addons_diretories:
      - configs
      - plugins
      - scripting
    addons_templates:
      - src: sm-cfg.j2
        dest: configs/skybox.ini
        data:
          skybox: "{{ sm_skybox_config | default({}) }}"
    other_files:
      - src: skybox/
        dest: materials/skybox