---

maplist: [de_inferno, de_train, de_mirage, de_nuke, de_overpass, de_dust2, de_vertigo, de_cache, de_cbble]
mapcycle: [de_inferno, de_train, de_mirage, de_nuke, de_overpass, de_dust2, de_vertigo, de_cache, de_cbble]