---

sm_cvars:
  server.cfg:
    - hostname: "{{ hostname }}"
    - game_type: 0
    - game_mode: 1
    - hostip: -1321822705 # 177.54.150.15
    - rcon_password: !vault |
        $ANSIBLE_VAULT;1.1;AES256
        63363066626637316266323938316334353262303765303137663731356132613035393463636265
        3732383162663231643462386136323832393937373730300a336362386332656265376439653438
        66393937653135323965373938396363613539383866663865313036663332323936613635663133
        3836373262646366350a316461376133306636663763623039666165626335306635366234656336
        6336
    - sv_region: 2
    - sv_prime_accounts_only: 0
    - sv_hibernate_when_empty: 1
    - sv_minrate: 128000
    - sv_mincmdrate: 128 # TODO: check on SURF
    - sv_minupdaterate: 128
    - mp_spectators_max: 0
    - mp_autokick: 0
    - mp_backup_round_auto: 0
    - log: 'on'
    - sv_logfile: 1
    - sv_logsdir: logs_source
    - sv_logecho: 0
    - sv_log_onefile: 1
    - sv_logbans: 1
    - sv_logdownloadlist: 1
    - sv_maxrate: 0
    - host_name_store: 1
    - host_info_show: 2
    - host_players_show: 2
    - exec: banned_user.cfg
    - exec: banned_ip.cfg
    - exec: performance.cfg
    - writeid:
    - writeip:
    - sv_max_queries_sec: 50
    - sv_max_queries_window: 10
    - sv_max_queries_sec_global: 1000
    - sv_downloadurl: "https://minio.epsilon.denerdtv.com/fastdl/csgo"
    - sv_allowdownload: 1
    - sv_allowupload: 1
    - sv_tags: kz,climb,pulo,jumpbr,brasil,brazil,deathmatch,ffa,dm,de_nerdtv,de_nerd,denerd,denerdtv,tdm,aim,treino,ws,glove,gloves,knife,knifes,knive,knives,skin,paint