---

hex_config:
  ScoreTag: ""
  ChatTag: ""

  # Anova
  STEAM_0:0:66095696:
    ScoreTag: "faketaxi "
    ChatTag: "faketaxi "

  # Example
  STEAM_0:1:36509127:
    ScoreTag: "Rank {rmRank} [DONO]"
    ChatTag: "{green}Rank {rmRank} {default}[{darkred}DONO{default}] "
    ChatColor: "{default}"
    NameColor: "{grey}"

  # Hidden tags
  o:
    ScoreTag: ""
    ChatTag: ""

  # Moderadores
  b:
    ScoreTag: "Rank {rmRank} [MODERADOR]"
    ChatTag: "{green}Rank {rmRank} {default}[{darkred}MODERADOR{default}] "

  # VIPs
  a:
    ScoreTag: "Rank {rmRank} [VIP]"
    ChatTag: "{green}Rank {rmRank} {default}[{darkred}VIP{default}] "